name: OSINT-Command-Search
on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Target Username to Pivot'
        required: true
        default: 'theosintvault'

jobs:
  investigate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: pip install aiohttp
      - name: Run Pivot Engine
        run: python core_crawler.py ${{ github.event.inputs.username }}
